name: Test CWL Files With Singularity

on:
  workflow_run:
    workflows: [Build and Push Docker Image]
    types: [completed]
    branches:
      - main
  workflow_dispatch:
jobs:
  list-tests:
    runs-on: ubuntu-latest
    steps:
    - name: List Files
      id: list-tests
      uses: bwbioinfo/list-files-action@main
      with:
        test-file-directory: tests
        inputs-file-extension: yml
        test-file-extension: cwl
    outputs:
      list-matrix: ${{ steps.list-tests.outputs.tests-matrix }}

  test-cwl-singularity:
    needs: list-tests
    strategy:
      matrix:
        tests: ${{ fromJson(needs.list-tests.outputs.list-matrix) }}
    runs-on: ubuntu-latest
    steps:
    - name: Test Singularity
      uses: bwbioinfo/singularity-cwl-action@main
      with:
        test-file: ${{ matrix.tests[0] }}
        inputs-file: ${{ matrix.tests[1] }}